### ISSUE TITLE
Background images vs. content

### ISSUE THREAD

**Issue by cvinczefullsail** [MayMalzahn/designing-for-web-standards-2#29]
You have included some images that should not be included in the HTML, like banner.jpg in the header of the icons in the Member Benefits section. Ask yourself if this image is essential for the understanding of the content of the page, and if not then don’t include it. Please see the feedback video and complete the HTML tutorial to better understand images vs. presentation:  https://7bc7b610b8d24a79a5da2f36e530df5a.codepen.website.

**Comment by MayMalzahn** [comment]
removed banner from HTML
