### ISSUE TITLE
Shop and Events pages

### ISSUE THREAD

**Issue by cvinczefullsail** [MayMalzahn/designing-for-web-standards-2#35]
Ask yourself if a product image, rating image, price, and an Add to Cart button would make sense on its own, without the context of the page. Not really. 

_What website is the product from? Where is there a description? What category would I find this?_

So a section would be a better choice than an article to match your inspirational screenshots for your Shop and Events pages.  Please see http://html5doctor.com/the-article-element/ for details.

**Comment by MayMalzahn** [comment]
Added more information to be filled from the JSON, the individual products now make more sense as individual articles
